### PR TITLE
Attribute and state threshold support 

### PR DESCRIPTION
**Pull request by jonnywray**
Hi,

added support for Riemann attributes and the ability to configure state thresholds for each metric. Default thresholds are the same as before.

Had to update to the current version of the Riemann client to get attributes to work.

J.

### CODE REVIEW

**Comment by ferhatsb** [comment]
I will accept that pull request due to given ability for configuring levels however actual right approach could be completely removing that decision out of this plugin and configure it at riemann server.

**Comment by jonnywray** [comment]
The support for attributes was more important to me honestly.

But, the setting of state via thresholds in the plugin follows the same
approach as riemann-health and associated tools. So the current approach of
this plugin is consistent with that. Personally, I haven't a strong feeling
yet for which is the right approach.

J.

**Comment by ferhatsb** [comment]
Don't get me wrong, we are also using this plugin as it is and developed after checking how others are doing. However changes on levels requires a node restart, instead it can be done at Riemann side without no changes at clients, that can be the main advantage. Thanks for PR.

**Comment by jonnywray** [comment]
That's a good point. I'm in the process of setting up our whole monitoring system so don't yet have a feel for how much of an issue those sorts of things will be. 

And thanks fir the work on the plugin, it's proved very useful. 

J.

**Pull request merged**
